# Netlify deployment configuration for a Slidev project

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Set the Node.js version to a recent, stable version.
  NODE_VERSION = "20"