# Run our new script to build all lessons automatically
[build]
  command = "bash build-all.sh"
  publish = "dist"

[build.environment]
  # Set the Node.js version to a recent, stable version.
  NODE_VERSION = "20"
