[build]
  # Build 'lesson-01.md' directly.
  command = "npx slidev build lesson-01.md"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Standard redirect rule for a single-page app like Slidev.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
